services:
  db:
    image: postgres:17.4-bookworm
    restart: always
    environment:
      POSTGRES_USER: uav_manager
      POSTGRES_PASSWORD: DVgt8pf4
      POSTGRES_DB: uav_manager_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uav_manager"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: info@carvalhais.ch
      PGADMIN_DEFAULT_PASSWORD: carvalhais
    ports:
      - "5050:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_NAME=uav_manager_db
      - POSTGRES_USER=uav_manager
      - POSTGRES_PASSWORD=DVgt8pf4
      - POSTGRES_HOST=db
      - DEBUG=True
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5175:5175"
    depends_on:
      - backend
    environment:
      - DOCKER=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
